name: node-js-labs Actions
on: push
jobs:
    preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - name: Install dependencies
              run: npm ci
            - name: Running Prettier
              run: npm run format
            - name: Running ESLint
              run: npm run lint
